name: API Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Run API tests
        run: ./gradlew apiTest

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-reports
          path: reports
