name: UI Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest


      - name: Setup Gradle Wrapper Permissions
        run: chmod +x gradlew

      - name: Run UI Tests
        run: ./gradlew webTest

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-test-reports
          path: reports
